// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WabiView.Data;

#nullable disable

namespace WabiView.Data.Migrations
{
    [DbContext(typeof(WabiViewDbContext))]
    partial class WabiViewDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("WabiView.Models.CoinjoinTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BlockHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("BlockHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Confirmations")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CoordinatorId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FeePaid")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("FeeRate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("TEXT");

                    b.Property<int>("InputCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OutputCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoundId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalInputValue")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalOutputValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TxId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("VSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BlockHeight");

                    b.HasIndex("CoordinatorId");

                    b.HasIndex("TxId")
                        .IsUnique();

                    b.ToTable("CoinjoinTransactions");
                });

            modelBuilder.Entity("WabiView.Models.Coordinator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailureCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("FeeRate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastChecked")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MinInputCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("Coordinators");
                });

            modelBuilder.Entity("WabiView.Models.Round", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoordinatorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("InputCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Phase")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoundId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TxId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.HasIndex("CoordinatorId", "RoundId")
                        .IsUnique();

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("WabiView.Models.CoinjoinTransaction", b =>
                {
                    b.HasOne("WabiView.Models.Coordinator", "Coordinator")
                        .WithMany("Coinjoins")
                        .HasForeignKey("CoordinatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Coordinator");
                });

            modelBuilder.Entity("WabiView.Models.Round", b =>
                {
                    b.HasOne("WabiView.Models.Coordinator", "Coordinator")
                        .WithMany("Rounds")
                        .HasForeignKey("CoordinatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coordinator");
                });

            modelBuilder.Entity("WabiView.Models.Coordinator", b =>
                {
                    b.Navigation("Coinjoins");

                    b.Navigation("Rounds");
                });
#pragma warning restore 612, 618
        }
    }
}
